version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: guardian_angel_db
      POSTGRES_USER: guardian_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/code/app
    expose:
      - "8000"
    depends_on:
      - db
    environment:
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=guardian_angel_db
      - DATABASE_USER=guardian_user
      - DATABASE_PASSWORD=securepassword
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    working_dir: /code/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app/staticfiles:/code/app/staticfiles
      - ./app/media:/code/app/media
    depends_on:
      - web

volumes:
  postgres_data: