# Generated by Django 5.1.3 on 2024-11-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrosswalkManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('extension_time', models.TimeField()),
                ('application_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crosswalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ctprvnNm', models.CharField(max_length=100)),
                ('signguNm', models.CharField(max_length=100)),
                ('roadNm', models.CharField(max_length=100)),
                ('rdnmadr', models.CharField(max_length=255)),
                ('lnmadr', models.CharField(max_length=255)),
                ('crslkManageNo', models.CharField(max_length=50)),
                ('crslkKnd', models.CharField(max_length=50)),
                ('bcyclCrslkCmbnatYn', models.BooleanField()),
                ('highlandYn', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cartrkCo', models.IntegerField()),
                ('bt', models.TimeField()),
                ('et', models.TimeField()),
                ('tfclghtYn', models.BooleanField()),
                ('fnctngSgngnrYn', models.BooleanField()),
                ('sondSgngnrYn', models.BooleanField()),
                ('greenSgngnrTime', models.TimeField()),
                ('redSgngnrTime', models.TimeField()),
                ('tfcilndYn', models.BooleanField()),
                ('ftpthLowerYn', models.BooleanField()),
                ('brllBlckYn', models.BooleanField()),
                ('cnctrLghtFcltyYn', models.BooleanField()),
                ('institutionNm', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('referenceDate', models.DateField()),
                ('instt_code', models.CharField(max_length=50)),
                ('instt_name', models.CharField(max_length=100)),
                ('increaseInGreenTime30', models.IntegerField(null=True)),
                ('increaseInGreenTime50', models.IntegerField(null=True)),
                ('management', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crosswalk', to='a_crosswalk.crosswalkmanagement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
