# Generated by Django 5.1.3 on 2024-11-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crosswalk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='instt_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
