# Generated by Django 5.1.3 on 2024-11-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_crosswalk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosswalk',
            name='applyTimeFrom',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='crosswalk',
            name='applyTimeTo',
            field=models.TimeField(null=True),
        ),
    ]
