# Generated by Django 5.1.3 on 2024-11-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_crosswalk', '0002_add_instt_name'),
        ('a_crosswalk', '0002_crosswalk_instt_name'),
    ]

    operations = [
    ]
